// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qg9BUJrNtisePZMs8FM4BQ
// Component: -EHwTOEw9V67

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Button2 from "../../Button2"; // plasmic-import: iFFcBUnvZUl0/component
import CaseStudiesSection from "../../CaseStudiesSection"; // plasmic-import: 8UZVGOKdExLM/component
import Testimonials from "../../Testimonials"; // plasmic-import: q8KVAm97HyX-/component
import FaqSection from "../../FaqSection"; // plasmic-import: BSnSueyvgk6P/component
import ConnectWithUs from "../../ConnectWithUs"; // plasmic-import: w9fJfCJ45KHV/component
import NavFooter from "../../NavFooter"; // plasmic-import: s0a682-ToGsq/component
import NavHeader from "../../NavHeader"; // plasmic-import: pZ9Yrp1wEL8X/component

import { useScreenVariants as useScreenVariantsptc9VYm7Ur9B } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PTC9vYM7UR9b/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_vidyayatan_landing_page_css from "../vidyayatan_landing_page/plasmic.module.css"; // plasmic-import: aqUnUFeSAtbFb77THsmBtm/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import plasmic_apple_css from "../apple/plasmic.module.css"; // plasmic-import: 3eY1qD8fYUzK6iRzHmP8VZ/projectcss
import plasmic_vercel_workflow_css from "../vercel_workflow/plasmic.module.css"; // plasmic-import: 9geyujr9Gmmnu34Qh9ic8E/projectcss
import plasmic_saa_s_website_css from "../saa_s_website/plasmic.module.css"; // plasmic-import: ybfbkvuYhwx2f8pSa8cKG/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qg9BUJrNtisePZMs8FM4BQ/projectcss
import sty from "./PlasmicArtificialIntelligence.module.css"; // plasmic-import: -EHwTOEw9V67/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: tSFoGfIVWAwT/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: FoPRmBUdi-FM/icon
import Frame16Icon from "./icons/PlasmicIcon__Frame16"; // plasmic-import: lTq5ZUD2xa6J/icon
import Frame51Icon from "./icons/PlasmicIcon__Frame51"; // plasmic-import: cA9AlvcOEqte/icon
import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: N64XRDanG7jJ/icon
import Frame27Icon from "./icons/PlasmicIcon__Frame27"; // plasmic-import: 9kE_v7ERYwed/icon
import Frame34Icon from "./icons/PlasmicIcon__Frame34"; // plasmic-import: SzohbHgr1-om/icon
import Frame37Icon from "./icons/PlasmicIcon__Frame37"; // plasmic-import: cB8KooTDO7hj/icon
import Frame38Icon from "./icons/PlasmicIcon__Frame38"; // plasmic-import: wLDga_XwdJ0e/icon
import Frame15Icon from "./icons/PlasmicIcon__Frame15"; // plasmic-import: YQCNU9xil-Ab/icon
import Frame52Icon from "./icons/PlasmicIcon__Frame52"; // plasmic-import: DfuXHJaWV0-a/icon

createPlasmicElementProxy;

export type PlasmicArtificialIntelligence__VariantMembers = {};
export type PlasmicArtificialIntelligence__VariantsArgs = {};
type VariantPropType = keyof PlasmicArtificialIntelligence__VariantsArgs;
export const PlasmicArtificialIntelligence__VariantProps =
  new Array<VariantPropType>();

export type PlasmicArtificialIntelligence__ArgsType = {
  q12?: React.ReactNode;
  q13?: React.ReactNode;
  q15?: React.ReactNode;
  q17?: React.ReactNode;
};
type ArgPropType = keyof PlasmicArtificialIntelligence__ArgsType;
export const PlasmicArtificialIntelligence__ArgProps = new Array<ArgPropType>(
  "q12",
  "q13",
  "q15",
  "q17"
);

export type PlasmicArtificialIntelligence__OverridesType = {
  root?: Flex__<"div">;
  heroSection?: Flex__<"section">;
  trustedBy?: Flex__<"section">;
  whyChooseVidyayatan?: Flex__<"section">;
  qualityProducts?: Flex__<"div">;
  frame427319326?: Flex__<"div">;
  frame427319327?: Flex__<"div">;
  qualityProducts2?: Flex__<"div">;
  frame427319334?: Flex__<"div">;
  frame427319335?: Flex__<"div">;
  qualityProducts3?: Flex__<"div">;
  frame427319336?: Flex__<"div">;
  frame427319337?: Flex__<"div">;
  whyVidyayatan?: Flex__<"section">;
  q1?: Flex__<"div">;
  q14?: Flex__<"div">;
  q16?: Flex__<"div">;
  q18?: Flex__<"div">;
  convertSection?: Flex__<"section">;
  aiUseCases?: Flex__<"section">;
  line?: Flex__<"div">;
  frame1000000975?: Flex__<"div">;
  frame427319348?: Flex__<"div">;
  line2?: Flex__<"div">;
  frame1000000977?: Flex__<"div">;
  frame427319349?: Flex__<"div">;
  line3?: Flex__<"div">;
  frame1000000979?: Flex__<"div">;
  frame427319330?: Flex__<"div">;
  line4?: Flex__<"div">;
  frame1000000984?: Flex__<"div">;
  frame427319331?: Flex__<"div">;
  line5?: Flex__<"div">;
  frame1000000987?: Flex__<"div">;
  frame427319332?: Flex__<"div">;
  caseStudiesSection?: Flex__<typeof CaseStudiesSection>;
  whyChooseVidyayatan2?: Flex__<"section">;
  qualityProducts4?: Flex__<"div">;
  frame427319338?: Flex__<"div">;
  frame427319339?: Flex__<"div">;
  qualityProducts5?: Flex__<"div">;
  frame427319340?: Flex__<"div">;
  frame427319341?: Flex__<"div">;
  qualityProducts6?: Flex__<"div">;
  frame427319342?: Flex__<"div">;
  frame427319343?: Flex__<"div">;
  testimonials?: Flex__<typeof Testimonials>;
  faqSection?: Flex__<typeof FaqSection>;
  connectWithUs?: Flex__<typeof ConnectWithUs>;
  navFooter?: Flex__<typeof NavFooter>;
  navHeader?: Flex__<typeof NavHeader>;
};

export interface DefaultArtificialIntelligenceProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicArtificialIntelligence__RenderFunc(props: {
  variants: PlasmicArtificialIntelligence__VariantsArgs;
  args: PlasmicArtificialIntelligence__ArgsType;
  overrides: PlasmicArtificialIntelligence__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsptc9VYm7Ur9B()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_vidyayatan_landing_page_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            plasmic_apple_css.plasmic_tokens,
            plasmic_vercel_workflow_css.plasmic_tokens,
            plasmic_saa_s_website_css.plasmic_tokens,
            sty.root
          )}
          onScroll={async event => {
            const $steps = {};
          }}
        >
          <section
            data-plasmic-name={"heroSection"}
            data-plasmic-override={overrides.heroSection}
            className={classNames(projectcss.all, sty.heroSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__wjGy3)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__yr5Vf)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pMd4X)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ek2Fo
                    )}
                  >
                    {"Skilled AI Engineers Ready"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b8JkB
                    )}
                  >
                    {
                      "Looking for expert AI engineers? Vidyayatan Technologies offers top-tier talent to help your company harness the power of artificial intelligence."
                    }
                  </div>
                </Stack__>
                <Button2
                  className={classNames("__wab_instance", sty.button2__c0RWk)}
                  link={"https://calendar.app.google/7GAyDKQLPvjA5rca6"}
                  shape={"rounded"}
                  showEndIcon={true}
                  target={true}
                >
                  {"Book meeting"}
                </Button2>
              </Stack__>
              <div className={classNames(projectcss.all, sty.column__fbQK)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__cIruM)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_mv_technologies_website/images/artificialIntelligenceHeroPng2.png",
                    fullWidth: 11636,
                    fullHeight: 10136,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"trustedBy"}
            data-plasmic-override={overrides.trustedBy}
            className={classNames(projectcss.all, sty.trustedBy)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___2Z4Ou)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y8DP1
                )}
              >
                {"Trusted by"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__h9GG)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__rugQe)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__zz0Cv)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__oeo70)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "auto"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/labourLinkLogo1Png2.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___984Tx)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__w4FCv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/habuildLogoPng3.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__pcwa3)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___0Zsno)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "28px"
                          : "auto"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/satvaaPng5.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__shKeb)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__onH2W)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/starBazzarLogoPng2.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___4FIrK)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column___06J7I)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__lfuoH)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "auto"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/maroiBoerderyBkLogoPng3.png",
                        fullWidth: 1116,
                        fullHeight: 192,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kv9Bs)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__d8KCa)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/innowellLogoPng3.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__ckAKs)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jsD7L)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/dcmShriRamPng2.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div className={classNames(projectcss.all, sty.column__eRIl)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__e2OEq)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/new_mv_technologies_website/images/bharatPeLogoPng2.png",
                        fullWidth: 425,
                        fullHeight: 80,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"whyChooseVidyayatan"}
            data-plasmic-override={overrides.whyChooseVidyayatan}
            className={classNames(projectcss.all, sty.whyChooseVidyayatan)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__tf0U)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aqTb2
                )}
              >
                {"Cutting-Edge AI Solutions"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aj0Ui
                )}
              >
                {
                  "Elevate your business with strategic AI consulting, expert engineering, and seamless integration from Vidyayatan. Stay ahead in the fast-evolving world of artificial intelligence."
                }
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__un7Jy)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__e4E9D)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts"}
                  data-plasmic-override={overrides.qualityProducts}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319326"}
                    data-plasmic-override={overrides.frame427319326}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319326)}
                  >
                    <Frame16Icon
                      className={classNames(projectcss.all, sty.svg__bddv)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319327"}
                    data-plasmic-override={overrides.frame427319327}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319327)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__erPjj
                      )}
                    >
                      {"Strategic AI Guidance"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xhYKl
                      )}
                    >
                      {
                        "Advance in the AI space with our comprehensive consulting services. We offer everything from tech stack solutions to a detailed strategic roadmap to ensure your success."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts2"}
                  data-plasmic-override={overrides.qualityProducts2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts2)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319334"}
                    data-plasmic-override={overrides.frame427319334}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319334)}
                  >
                    <Frame51Icon
                      className={classNames(projectcss.all, sty.svg__naYTl)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319335"}
                    data-plasmic-override={overrides.frame427319335}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319335)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1stOi
                      )}
                    >
                      {"Custom AI Engineering"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kpYo
                      )}
                    >
                      {
                        "Personalized AI solutions designed to tackle your business challenges. Reliable, secure, and scalable\u2014discover our engineering expertise."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts3"}
                  data-plasmic-override={overrides.qualityProducts3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts3)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319336"}
                    data-plasmic-override={overrides.frame427319336}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319336)}
                  >
                    <FrameIcon
                      className={classNames(projectcss.all, sty.svg__gQubh)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319337"}
                    data-plasmic-override={overrides.frame427319337}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319337)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__t5Y54
                      )}
                    >
                      {"AI-Powered Integration "}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__et3Nz
                      )}
                    >
                      {
                        "Revolutionize your operations with AI integration. Seamlessly automate and accelerate processes to boost efficiency and productivity."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <div className={classNames(projectcss.all, sty.column__bYc4)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__refo1)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_mv_technologies_website/images/_2304I039017FM004C9AiGeneratedArtAiPoweredContentCreationIsometricConverted1Png2.png",
                    fullWidth: 2484,
                    fullHeight: 2408,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"whyVidyayatan"}
            data-plasmic-override={overrides.whyVidyayatan}
            className={classNames(projectcss.all, sty.whyVidyayatan)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__iZjGd)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xadRo
                )}
              >
                {"Cost-Effective AI Solutions"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eSoIa
                )}
              >
                {
                  "Adopting Artificial Intelligence (AI) represents a crucial step for businesses, opening doors to numerous advantages in today\u2019s dynamic market. With enhanced efficiency and improved customer experiences, AI delivers exceptional potential for progress and innovation."
                }
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__pNiiq)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__rAm5)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"q1"}
                  data-plasmic-override={overrides.q1}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.q1)}
                >
                  {renderPlasmicSlot({
                    defaultContents: (
                      <Frame27Icon
                        className={classNames(projectcss.all, sty.svg___3U47)}
                        role={"img"}
                      />
                    ),

                    value: args.q12
                  })}
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6Xj7T)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___32Cof
                    )}
                  >
                    {"Automated Processes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bKZm
                    )}
                  >
                    {
                      "Enhance efficiency by automating routine tasks with AI. Free up time and resources for strategic goals, improving productivity and minimizing errors."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__uPAvn)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"q14"}
                  data-plasmic-override={overrides.q14}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.q14)}
                >
                  {renderPlasmicSlot({
                    defaultContents: (
                      <Frame34Icon
                        className={classNames(projectcss.all, sty.svg__iZXd7)}
                        role={"img"}
                      />
                    ),

                    value: args.q13
                  })}
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hjWv)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bnAd
                    )}
                  >
                    {"Real-Time Data Insights"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___89ZY
                    )}
                  >
                    {
                      "Employ AI to rapidly process extensive data volumes. Unlock valuable insights for strategic decisions, trend analysis, and predictive modeling."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__unWzG)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"q16"}
                  data-plasmic-override={overrides.q16}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.q16)}
                >
                  {renderPlasmicSlot({
                    defaultContents: (
                      <FrameIcon
                        className={classNames(projectcss.all, sty.svg__yrdEp)}
                        role={"img"}
                      />
                    ),

                    value: args.q15
                  })}
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___0MjwT)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lJn5B
                    )}
                  >
                    {"Integrated Digital Resources"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aabHg
                    )}
                  >
                    {
                      "Leverage AI to consolidate and oversee digital assets across various platforms, maintaining brand consistency and enriching customer experiences."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__qx8Ua)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"q18"}
                  data-plasmic-override={overrides.q18}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.q18)}
                >
                  {renderPlasmicSlot({
                    defaultContents: (
                      <Frame37Icon
                        className={classNames(projectcss.all, sty.svg__pmEcL)}
                        role={"img"}
                      />
                    ),

                    value: args.q17
                  })}
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__koDqZ)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oc2Zm
                    )}
                  >
                    {"Enhanced Customer Interactions"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___47Kv
                    )}
                  >
                    {
                      "Improve client engagement with tailored AI-driven solutions, strengthening relationships and boosting loyalty."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"convertSection"}
            data-plasmic-override={overrides.convertSection}
            className={classNames(projectcss.all, sty.convertSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__oNma)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5Krle
                )}
              >
                {"Seeking Cost-Effective AI Solutions?"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___19Ih)}
            >
              <div className={classNames(projectcss.all, sty.column__nhSC)}>
                <Button2
                  className={classNames("__wab_instance", sty.button2___9Qx4Z)}
                  color={"white"}
                  link={`/pricing-page`}
                  shape={"rounded"}
                >
                  {"View Pricing"}
                </Button2>
              </div>
              <div className={classNames(projectcss.all, sty.column__z3XRl)}>
                <Button2
                  className={classNames("__wab_instance", sty.button2__fNr6A)}
                  color={undefined}
                  link={"https://calendar.app.google/7GAyDKQLPvjA5rca6"}
                  shape={"rounded"}
                  showEndIcon={true}
                  target={true}
                >
                  {"Book Meeting"}
                </Button2>
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"aiUseCases"}
            data-plasmic-override={overrides.aiUseCases}
            className={classNames(projectcss.all, sty.aiUseCases)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__oyuGc)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0EFiO
                )}
              >
                {"Practical AI Implementations"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__fdaem)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__iLsBv)}
              >
                <div
                  data-plasmic-name={"line"}
                  data-plasmic-override={overrides.line}
                  className={classNames(projectcss.all, sty.line)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000975"}
                    data-plasmic-override={overrides.frame1000000975}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000975)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kdr33
                      )}
                    >
                      {"1"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319348"}
                  data-plasmic-override={overrides.frame427319348}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319348)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vjYpU
                    )}
                  >
                    {"Enhancing Customer Experience with AI"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__su3H5
                    )}
                  >
                    {
                      "Elevate your organization\u2019s customer interactions by integrating AI technology to deliver personalized and responsive service."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xBhW)}
              >
                <div
                  data-plasmic-name={"line2"}
                  data-plasmic-override={overrides.line2}
                  className={classNames(projectcss.all, sty.line2)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000977"}
                    data-plasmic-override={overrides.frame1000000977}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000977)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wpYxs
                      )}
                    >
                      {"2"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319349"}
                  data-plasmic-override={overrides.frame427319349}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319349)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xxfYa
                    )}
                  >
                    {"Modernizing Applications with AI"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p6TFx
                    )}
                  >
                    {
                      "Update your application framework with AI-driven approaches, offering smarter management and efficient hybrid cloud solutions."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__d4Ivr)}
              >
                <div
                  data-plasmic-name={"line3"}
                  data-plasmic-override={overrides.line3}
                  className={classNames(projectcss.all, sty.line3)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000979"}
                    data-plasmic-override={overrides.frame1000000979}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000979)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nBk3J
                      )}
                    >
                      {"3"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319330"}
                  data-plasmic-override={overrides.frame427319330}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319330)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m9Vau
                    )}
                  >
                    {"AI-Driven Marketing Innovations"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ojd0D
                    )}
                  >
                    {
                      "Transform your marketing strategy using AI to analyze customer behavior and preferences, optimize content, and refine your approach."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ozZUm)}
              >
                <div
                  data-plasmic-name={"line4"}
                  data-plasmic-override={overrides.line4}
                  className={classNames(projectcss.all, sty.line4)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000984"}
                    data-plasmic-override={overrides.frame1000000984}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000984)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fD2GH
                      )}
                    >
                      {"4"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319331"}
                  data-plasmic-override={overrides.frame427319331}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319331)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rAR
                    )}
                  >
                    {"Optimizing Talent Management with AI"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lHsUo
                    )}
                  >
                    {
                      "Boost workforce productivity and efficiency with AI-powered HR solutions tailored to enhance talent management and organizational performance."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__iU5Yb)}
              >
                <div
                  data-plasmic-name={"line5"}
                  data-plasmic-override={overrides.line5}
                  className={classNames(projectcss.all, sty.line5)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000987"}
                    data-plasmic-override={overrides.frame1000000987}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000987)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rxMjk
                      )}
                    >
                      {"5"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319332"}
                  data-plasmic-override={overrides.frame427319332}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319332)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cRyPo
                    )}
                  >
                    {"AI-Enhanced Financial Operations"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7O2Pl
                    )}
                  >
                    {
                      "Leverage AI for advanced analytics to improve financial forecasting, performance measurement, and decision-making in your finance operations."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <CaseStudiesSection
            data-plasmic-name={"caseStudiesSection"}
            data-plasmic-override={overrides.caseStudiesSection}
            className={classNames("__wab_instance", sty.caseStudiesSection)}
          />

          <section
            data-plasmic-name={"whyChooseVidyayatan2"}
            data-plasmic-override={overrides.whyChooseVidyayatan2}
            className={classNames(projectcss.all, sty.whyChooseVidyayatan2)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__a2NkI)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bz9Jb
                )}
              >
                {"AI Solutions by Vidyayatan Technologies"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ufr1V
                )}
              >
                {
                  "Our AI services are designed to deliver dependable and innovative solutions, focusing on optimizing AI operations and fostering growth. We specialize in integrating advanced AI analytics, automating workflows, and enabling businesses to excel in a rapidly evolving environment."
                }
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xlC3M)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__jKo6Z)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts4"}
                  data-plasmic-override={overrides.qualityProducts4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts4)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319338"}
                    data-plasmic-override={overrides.frame427319338}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319338)}
                  >
                    <Frame38Icon
                      className={classNames(projectcss.all, sty.svg__iqVjJ)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319339"}
                    data-plasmic-override={overrides.frame427319339}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319339)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pBh96
                      )}
                    >
                      {"AI-Powered Data and Analytics Development"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ii5WQ
                      )}
                    >
                      {
                        "Integrate your enterprise data to build robust digital, operational, analytical, and AI models. Leverage deep learning and enhance efficiency with smart, automated workflows."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts5"}
                  data-plasmic-override={overrides.qualityProducts5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts5)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319340"}
                    data-plasmic-override={overrides.frame427319340}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319340)}
                  >
                    <Frame15Icon
                      className={classNames(projectcss.all, sty.svg__aqihF)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319341"}
                    data-plasmic-override={overrides.frame427319341}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319341)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sItZk
                      )}
                    >
                      {"AI-Driven Workflow Automation"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tfgNx
                      )}
                    >
                      {
                        "Automate and digitize workflows with AI, creating seamless processes powered by a hybrid workforce."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts6"}
                  data-plasmic-override={overrides.qualityProducts6}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts6)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319342"}
                    data-plasmic-override={overrides.frame427319342}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319342)}
                  >
                    <Frame52Icon
                      className={classNames(projectcss.all, sty.svg__dGq6N)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319343"}
                    data-plasmic-override={overrides.frame427319343}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319343)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__r3R2A
                      )}
                    >
                      {"AI-Enhanced Cloud Solutions"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wga7
                      )}
                    >
                      {
                        "Boost efficiency and reduce costs with AI and automation. We manage your hybrid cloud applications, driving optimisation and higher ROI."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <div className={classNames(projectcss.all, sty.column__h6KUe)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__okzYj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_mv_technologies_website/images/_2106I201007FM004C9CallCenterTechnicalSupportIsometricConverted1Png.png",
                    fullWidth: 1800,
                    fullHeight: 2004,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>
          <Testimonials
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            className={classNames("__wab_instance", sty.testimonials)}
          />

          <FaqSection
            data-plasmic-name={"faqSection"}
            data-plasmic-override={overrides.faqSection}
            className={classNames("__wab_instance", sty.faqSection)}
          />

          <ConnectWithUs
            data-plasmic-name={"connectWithUs"}
            data-plasmic-override={overrides.connectWithUs}
            className={classNames("__wab_instance", sty.connectWithUs)}
          />

          <NavFooter
            data-plasmic-name={"navFooter"}
            data-plasmic-override={overrides.navFooter}
            className={classNames("__wab_instance", sty.navFooter)}
          />

          <NavHeader
            data-plasmic-name={"navHeader"}
            data-plasmic-override={overrides.navHeader}
            className={classNames("__wab_instance", sty.navHeader)}
            scrolledVariant={(() => {
              try {
                return $ctx.isScrolled;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection",
    "trustedBy",
    "whyChooseVidyayatan",
    "qualityProducts",
    "frame427319326",
    "frame427319327",
    "qualityProducts2",
    "frame427319334",
    "frame427319335",
    "qualityProducts3",
    "frame427319336",
    "frame427319337",
    "whyVidyayatan",
    "q1",
    "q14",
    "q16",
    "q18",
    "convertSection",
    "aiUseCases",
    "line",
    "frame1000000975",
    "frame427319348",
    "line2",
    "frame1000000977",
    "frame427319349",
    "line3",
    "frame1000000979",
    "frame427319330",
    "line4",
    "frame1000000984",
    "frame427319331",
    "line5",
    "frame1000000987",
    "frame427319332",
    "caseStudiesSection",
    "whyChooseVidyayatan2",
    "qualityProducts4",
    "frame427319338",
    "frame427319339",
    "qualityProducts5",
    "frame427319340",
    "frame427319341",
    "qualityProducts6",
    "frame427319342",
    "frame427319343",
    "testimonials",
    "faqSection",
    "connectWithUs",
    "navFooter",
    "navHeader"
  ],
  heroSection: ["heroSection"],
  trustedBy: ["trustedBy"],
  whyChooseVidyayatan: [
    "whyChooseVidyayatan",
    "qualityProducts",
    "frame427319326",
    "frame427319327",
    "qualityProducts2",
    "frame427319334",
    "frame427319335",
    "qualityProducts3",
    "frame427319336",
    "frame427319337"
  ],
  qualityProducts: ["qualityProducts", "frame427319326", "frame427319327"],
  frame427319326: ["frame427319326"],
  frame427319327: ["frame427319327"],
  qualityProducts2: ["qualityProducts2", "frame427319334", "frame427319335"],
  frame427319334: ["frame427319334"],
  frame427319335: ["frame427319335"],
  qualityProducts3: ["qualityProducts3", "frame427319336", "frame427319337"],
  frame427319336: ["frame427319336"],
  frame427319337: ["frame427319337"],
  whyVidyayatan: ["whyVidyayatan", "q1", "q14", "q16", "q18"],
  q1: ["q1"],
  q14: ["q14"],
  q16: ["q16"],
  q18: ["q18"],
  convertSection: ["convertSection"],
  aiUseCases: [
    "aiUseCases",
    "line",
    "frame1000000975",
    "frame427319348",
    "line2",
    "frame1000000977",
    "frame427319349",
    "line3",
    "frame1000000979",
    "frame427319330",
    "line4",
    "frame1000000984",
    "frame427319331",
    "line5",
    "frame1000000987",
    "frame427319332"
  ],
  line: ["line", "frame1000000975"],
  frame1000000975: ["frame1000000975"],
  frame427319348: ["frame427319348"],
  line2: ["line2", "frame1000000977"],
  frame1000000977: ["frame1000000977"],
  frame427319349: ["frame427319349"],
  line3: ["line3", "frame1000000979"],
  frame1000000979: ["frame1000000979"],
  frame427319330: ["frame427319330"],
  line4: ["line4", "frame1000000984"],
  frame1000000984: ["frame1000000984"],
  frame427319331: ["frame427319331"],
  line5: ["line5", "frame1000000987"],
  frame1000000987: ["frame1000000987"],
  frame427319332: ["frame427319332"],
  caseStudiesSection: ["caseStudiesSection"],
  whyChooseVidyayatan2: [
    "whyChooseVidyayatan2",
    "qualityProducts4",
    "frame427319338",
    "frame427319339",
    "qualityProducts5",
    "frame427319340",
    "frame427319341",
    "qualityProducts6",
    "frame427319342",
    "frame427319343"
  ],
  qualityProducts4: ["qualityProducts4", "frame427319338", "frame427319339"],
  frame427319338: ["frame427319338"],
  frame427319339: ["frame427319339"],
  qualityProducts5: ["qualityProducts5", "frame427319340", "frame427319341"],
  frame427319340: ["frame427319340"],
  frame427319341: ["frame427319341"],
  qualityProducts6: ["qualityProducts6", "frame427319342", "frame427319343"],
  frame427319342: ["frame427319342"],
  frame427319343: ["frame427319343"],
  testimonials: ["testimonials"],
  faqSection: ["faqSection"],
  connectWithUs: ["connectWithUs"],
  navFooter: ["navFooter"],
  navHeader: ["navHeader"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroSection: "section";
  trustedBy: "section";
  whyChooseVidyayatan: "section";
  qualityProducts: "div";
  frame427319326: "div";
  frame427319327: "div";
  qualityProducts2: "div";
  frame427319334: "div";
  frame427319335: "div";
  qualityProducts3: "div";
  frame427319336: "div";
  frame427319337: "div";
  whyVidyayatan: "section";
  q1: "div";
  q14: "div";
  q16: "div";
  q18: "div";
  convertSection: "section";
  aiUseCases: "section";
  line: "div";
  frame1000000975: "div";
  frame427319348: "div";
  line2: "div";
  frame1000000977: "div";
  frame427319349: "div";
  line3: "div";
  frame1000000979: "div";
  frame427319330: "div";
  line4: "div";
  frame1000000984: "div";
  frame427319331: "div";
  line5: "div";
  frame1000000987: "div";
  frame427319332: "div";
  caseStudiesSection: typeof CaseStudiesSection;
  whyChooseVidyayatan2: "section";
  qualityProducts4: "div";
  frame427319338: "div";
  frame427319339: "div";
  qualityProducts5: "div";
  frame427319340: "div";
  frame427319341: "div";
  qualityProducts6: "div";
  frame427319342: "div";
  frame427319343: "div";
  testimonials: typeof Testimonials;
  faqSection: typeof FaqSection;
  connectWithUs: typeof ConnectWithUs;
  navFooter: typeof NavFooter;
  navHeader: typeof NavHeader;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArtificialIntelligence__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArtificialIntelligence__VariantsArgs;
    args?: PlasmicArtificialIntelligence__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicArtificialIntelligence__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicArtificialIntelligence__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicArtificialIntelligence__ArgProps,
          internalVariantPropNames: PlasmicArtificialIntelligence__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicArtificialIntelligence__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArtificialIntelligence";
  } else {
    func.displayName = `PlasmicArtificialIntelligence.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "qg9BUJrNtisePZMs8FM4BQ"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicArtificialIntelligence = Object.assign(
  // Top-level PlasmicArtificialIntelligence renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    heroSection: makeNodeComponent("heroSection"),
    trustedBy: makeNodeComponent("trustedBy"),
    whyChooseVidyayatan: makeNodeComponent("whyChooseVidyayatan"),
    qualityProducts: makeNodeComponent("qualityProducts"),
    frame427319326: makeNodeComponent("frame427319326"),
    frame427319327: makeNodeComponent("frame427319327"),
    qualityProducts2: makeNodeComponent("qualityProducts2"),
    frame427319334: makeNodeComponent("frame427319334"),
    frame427319335: makeNodeComponent("frame427319335"),
    qualityProducts3: makeNodeComponent("qualityProducts3"),
    frame427319336: makeNodeComponent("frame427319336"),
    frame427319337: makeNodeComponent("frame427319337"),
    whyVidyayatan: makeNodeComponent("whyVidyayatan"),
    q1: makeNodeComponent("q1"),
    q14: makeNodeComponent("q14"),
    q16: makeNodeComponent("q16"),
    q18: makeNodeComponent("q18"),
    convertSection: makeNodeComponent("convertSection"),
    aiUseCases: makeNodeComponent("aiUseCases"),
    line: makeNodeComponent("line"),
    frame1000000975: makeNodeComponent("frame1000000975"),
    frame427319348: makeNodeComponent("frame427319348"),
    line2: makeNodeComponent("line2"),
    frame1000000977: makeNodeComponent("frame1000000977"),
    frame427319349: makeNodeComponent("frame427319349"),
    line3: makeNodeComponent("line3"),
    frame1000000979: makeNodeComponent("frame1000000979"),
    frame427319330: makeNodeComponent("frame427319330"),
    line4: makeNodeComponent("line4"),
    frame1000000984: makeNodeComponent("frame1000000984"),
    frame427319331: makeNodeComponent("frame427319331"),
    line5: makeNodeComponent("line5"),
    frame1000000987: makeNodeComponent("frame1000000987"),
    frame427319332: makeNodeComponent("frame427319332"),
    caseStudiesSection: makeNodeComponent("caseStudiesSection"),
    whyChooseVidyayatan2: makeNodeComponent("whyChooseVidyayatan2"),
    qualityProducts4: makeNodeComponent("qualityProducts4"),
    frame427319338: makeNodeComponent("frame427319338"),
    frame427319339: makeNodeComponent("frame427319339"),
    qualityProducts5: makeNodeComponent("qualityProducts5"),
    frame427319340: makeNodeComponent("frame427319340"),
    frame427319341: makeNodeComponent("frame427319341"),
    qualityProducts6: makeNodeComponent("qualityProducts6"),
    frame427319342: makeNodeComponent("frame427319342"),
    frame427319343: makeNodeComponent("frame427319343"),
    testimonials: makeNodeComponent("testimonials"),
    faqSection: makeNodeComponent("faqSection"),
    connectWithUs: makeNodeComponent("connectWithUs"),
    navFooter: makeNodeComponent("navFooter"),
    navHeader: makeNodeComponent("navHeader"),

    // Metadata about props expected for PlasmicArtificialIntelligence
    internalVariantProps: PlasmicArtificialIntelligence__VariantProps,
    internalArgProps: PlasmicArtificialIntelligence__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicArtificialIntelligence;
/* prettier-ignore-end */
