// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qg9BUJrNtisePZMs8FM4BQ
// Component: 4F5josqYEdVC

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Button2 from "../../Button2"; // plasmic-import: iFFcBUnvZUl0/component
import ConnectWithUs from "../../ConnectWithUs"; // plasmic-import: w9fJfCJ45KHV/component
import NavFooter from "../../NavFooter"; // plasmic-import: s0a682-ToGsq/component
import NavHeader from "../../NavHeader"; // plasmic-import: pZ9Yrp1wEL8X/component

import { useScreenVariants as useScreenVariantsptc9VYm7Ur9B } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PTC9vYM7UR9b/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_vidyayatan_landing_page_css from "../vidyayatan_landing_page/plasmic.module.css"; // plasmic-import: aqUnUFeSAtbFb77THsmBtm/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import plasmic_apple_css from "../apple/plasmic.module.css"; // plasmic-import: 3eY1qD8fYUzK6iRzHmP8VZ/projectcss
import plasmic_vercel_workflow_css from "../vercel_workflow/plasmic.module.css"; // plasmic-import: 9geyujr9Gmmnu34Qh9ic8E/projectcss
import plasmic_saa_s_website_css from "../saa_s_website/plasmic.module.css"; // plasmic-import: ybfbkvuYhwx2f8pSa8cKG/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qg9BUJrNtisePZMs8FM4BQ/projectcss
import sty from "./PlasmicEdtechPage.module.css"; // plasmic-import: 4F5josqYEdVC/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: tSFoGfIVWAwT/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: FoPRmBUdi-FM/icon
import Frame59Icon from "./icons/PlasmicIcon__Frame59"; // plasmic-import: hOYbrHdpxbtl/icon
import Frame15Icon from "./icons/PlasmicIcon__Frame15"; // plasmic-import: YQCNU9xil-Ab/icon
import Frame24Icon from "./icons/PlasmicIcon__Frame24"; // plasmic-import: PYD8IjXZxJnA/icon
import Frame34Icon from "./icons/PlasmicIcon__Frame34"; // plasmic-import: SzohbHgr1-om/icon
import Frame51Icon from "./icons/PlasmicIcon__Frame51"; // plasmic-import: cA9AlvcOEqte/icon
import Frame30Icon from "./icons/PlasmicIcon__Frame30"; // plasmic-import: VFIXgdenzVs0/icon
import Frame25Icon from "./icons/PlasmicIcon__Frame25"; // plasmic-import: JX3DLIHojP5f/icon
import Frame16Icon from "./icons/PlasmicIcon__Frame16"; // plasmic-import: lTq5ZUD2xa6J/icon
import Frame55Icon from "./icons/PlasmicIcon__Frame55"; // plasmic-import: QSO5mDHHHMUu/icon
import Frame50Icon from "./icons/PlasmicIcon__Frame50"; // plasmic-import: Jl22KJcan1vr/icon
import Frame18Icon from "./icons/PlasmicIcon__Frame18"; // plasmic-import: n4n-qgslZ89z/icon

createPlasmicElementProxy;

export type PlasmicEdtechPage__VariantMembers = {};
export type PlasmicEdtechPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicEdtechPage__VariantsArgs;
export const PlasmicEdtechPage__VariantProps = new Array<VariantPropType>();

export type PlasmicEdtechPage__ArgsType = {
  q12?: React.ReactNode;
  q13?: React.ReactNode;
  q15?: React.ReactNode;
  q17?: React.ReactNode;
  q18?: React.ReactNode;
  q19?: React.ReactNode;
};
type ArgPropType = keyof PlasmicEdtechPage__ArgsType;
export const PlasmicEdtechPage__ArgProps = new Array<ArgPropType>(
  "q12",
  "q13",
  "q15",
  "q17",
  "q18",
  "q19"
);

export type PlasmicEdtechPage__OverridesType = {
  root?: Flex__<"div">;
  heroSection?: Flex__<"section">;
  whyChooseVidyayatan?: Flex__<"section">;
  qualityProducts?: Flex__<"div">;
  frame427319326?: Flex__<"div">;
  frame427319327?: Flex__<"div">;
  qualityProducts2?: Flex__<"div">;
  frame427319328?: Flex__<"div">;
  frame427319329?: Flex__<"div">;
  qualityProducts3?: Flex__<"div">;
  frame427319330?: Flex__<"div">;
  frame427319331?: Flex__<"div">;
  convertSection?: Flex__<"section">;
  whyChooseVidyayatan2?: Flex__<"section">;
  qualityProducts4?: Flex__<"div">;
  frame427319332?: Flex__<"div">;
  frame427319333?: Flex__<"div">;
  qualityProducts5?: Flex__<"div">;
  frame427319334?: Flex__<"div">;
  frame427319335?: Flex__<"div">;
  qualityProducts6?: Flex__<"div">;
  frame427319336?: Flex__<"div">;
  frame427319337?: Flex__<"div">;
  qualityProducts7?: Flex__<"div">;
  frame427319338?: Flex__<"div">;
  frame427319339?: Flex__<"div">;
  edtechSolutions?: Flex__<"section">;
  q1?: Flex__<"div">;
  q14?: Flex__<"div">;
  q16?: Flex__<"div">;
  q110?: Flex__<"div">;
  q111?: Flex__<"div">;
  q112?: Flex__<"div">;
  emergingTechnologies?: Flex__<"section">;
  ourServices?: Flex__<"div">;
  outsourcingSoftware2?: Flex__<"div">;
  text8?: Flex__<"div">;
  text10?: Flex__<"div">;
  text11?: Flex__<"div">;
  outsourcingSoftware4?: Flex__<"div">;
  text12?: Flex__<"div">;
  text13?: Flex__<"div">;
  text14?: Flex__<"div">;
  devOpsUseCases?: Flex__<"section">;
  line?: Flex__<"div">;
  frame1000000975?: Flex__<"div">;
  frame427319348?: Flex__<"div">;
  line2?: Flex__<"div">;
  frame1000000977?: Flex__<"div">;
  frame427319349?: Flex__<"div">;
  line3?: Flex__<"div">;
  frame1000000979?: Flex__<"div">;
  frame427319340?: Flex__<"div">;
  line4?: Flex__<"div">;
  frame1000000984?: Flex__<"div">;
  frame427319341?: Flex__<"div">;
  line5?: Flex__<"div">;
  frame1000000987?: Flex__<"div">;
  frame427319342?: Flex__<"div">;
  line6?: Flex__<"div">;
  frame1000000988?: Flex__<"div">;
  frame427319343?: Flex__<"div">;
  line7?: Flex__<"div">;
  frame1000000989?: Flex__<"div">;
  frame427319344?: Flex__<"div">;
  connectWithUs?: Flex__<typeof ConnectWithUs>;
  navFooter?: Flex__<typeof NavFooter>;
  navHeader?: Flex__<typeof NavHeader>;
};

export interface DefaultEdtechPageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEdtechPage__RenderFunc(props: {
  variants: PlasmicEdtechPage__VariantsArgs;
  args: PlasmicEdtechPage__ArgsType;
  overrides: PlasmicEdtechPage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsptc9VYm7Ur9B()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_vidyayatan_landing_page_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            plasmic_apple_css.plasmic_tokens,
            plasmic_vercel_workflow_css.plasmic_tokens,
            plasmic_saa_s_website_css.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"heroSection"}
            data-plasmic-override={overrides.heroSection}
            className={classNames(projectcss.all, sty.heroSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__aEtfn)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__w9Ct)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__t3HPl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fiT8Z
                    )}
                  >
                    {"Revolutionizing Education with Smart Learning Solutions"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r3Ugu
                    )}
                  >
                    {
                      "Custom software crafted for success. With scalable, secure, and cost-effective solutions, we provide seamless integration that ensures your business achieves real ROI."
                    }
                  </div>
                </Stack__>
                <Button2
                  className={classNames("__wab_instance", sty.button2__mweci)}
                  link={"https://calendar.app.google/7GAyDKQLPvjA5rca6"}
                  shape={"rounded"}
                  showEndIcon={true}
                  target={true}
                >
                  {"Book meeting"}
                </Button2>
              </Stack__>
              <div className={classNames(projectcss.all, sty.column__ydhgN)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ujHbt)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_mv_technologies_website/images/image64.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"whyChooseVidyayatan"}
            data-plasmic-override={overrides.whyChooseVidyayatan}
            className={classNames(projectcss.all, sty.whyChooseVidyayatan)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__boUoi)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mku4P
                )}
              >
                {"Unlock the Power of Learning"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__l8Bi
                )}
              >
                {
                  "Our EdTech platform transforms learning by providing adaptive, engaging tools that meet diverse student needs. It empowers educators to streamline processes and make data-driven decisions, while offering students immersive, personalized, and collaborative learning experiences, both in the classroom and remotely."
                }
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__pbIah)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__mch2C)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts"}
                  data-plasmic-override={overrides.qualityProducts}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319326"}
                    data-plasmic-override={overrides.frame427319326}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319326)}
                  >
                    <Frame59Icon
                      className={classNames(projectcss.all, sty.svg__wIyF)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319327"}
                    data-plasmic-override={overrides.frame427319327}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319327)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tP8PW
                      )}
                    >
                      {"Personalized Learning"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bobN7
                      )}
                    >
                      {
                        "Tailor learning experiences to each student's unique needs and abilities using AI-driven algorithms."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts2"}
                  data-plasmic-override={overrides.qualityProducts2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts2)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319328"}
                    data-plasmic-override={overrides.frame427319328}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319328)}
                  >
                    <Frame15Icon
                      className={classNames(projectcss.all, sty.svg___7GqF)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319329"}
                    data-plasmic-override={overrides.frame427319329}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319329)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4J2Am
                      )}
                    >
                      {"Content Management System (CMS)"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1AmJi
                      )}
                    >
                      {
                        "Easily organize, distribute, and manage educational content for seamless access."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts3"}
                  data-plasmic-override={overrides.qualityProducts3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts3)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319330"}
                    data-plasmic-override={overrides.frame427319330}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319330)}
                  >
                    <Frame24Icon
                      className={classNames(projectcss.all, sty.svg__cpxhg)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319331"}
                    data-plasmic-override={overrides.frame427319331}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319331)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kFCut
                      )}
                    >
                      {"Interactive Learning Tools"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ulWf3
                      )}
                    >
                      {
                        "Engage students with virtual labs, simulations, gamified quizzes, and interactive videos."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <div className={classNames(projectcss.all, sty.column___58Ajx)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wJ2H)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_mv_technologies_website/images/image65.png",
                    fullWidth: 4788,
                    fullHeight: 4800,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"convertSection"}
            data-plasmic-override={overrides.convertSection}
            className={classNames(projectcss.all, sty.convertSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ctnrX)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xtmYr
                )}
              >
                {"\nLooking for the Best Value in EdTech Solutions?"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___0OfaU)}
            >
              <div className={classNames(projectcss.all, sty.column__oNtRs)}>
                <Button2
                  className={classNames("__wab_instance", sty.button2__urIc8)}
                  color={"white"}
                  link={`/pricing-page`}
                  shape={"rounded"}
                >
                  {"View Pricing"}
                </Button2>
              </div>
              <div className={classNames(projectcss.all, sty.column__kLhV3)}>
                <Button2
                  className={classNames("__wab_instance", sty.button2__kte14)}
                  color={undefined}
                  link={"https://calendar.app.google/7GAyDKQLPvjA5rca6"}
                  shape={"rounded"}
                  showEndIcon={true}
                >
                  {"Book Meeting"}
                </Button2>
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"whyChooseVidyayatan2"}
            data-plasmic-override={overrides.whyChooseVidyayatan2}
            className={classNames(projectcss.all, sty.whyChooseVidyayatan2)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gmX6K)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5NUc
                )}
              >
                {"Shaping the Future of Education"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___75P7
                )}
              >
                {
                  "Our EdTech platform revolutionizes learning with adaptive and engaging tools that cater to diverse student needs. It enables educators to simplify tasks and make informed, data-driven decisions, while providing students with personalized, immersive, and collaborative learning experiences, whether in the classroom or online."
                }
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__sUvZm)}
            >
              <div className={classNames(projectcss.all, sty.column___5Oo05)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vf0Ke)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/new_mv_technologies_website/images/image66.png",
                    fullWidth: 4720,
                    fullHeight: 4800,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__gtRcE)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts4"}
                  data-plasmic-override={overrides.qualityProducts4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts4)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319332"}
                    data-plasmic-override={overrides.frame427319332}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319332)}
                  >
                    <Frame24Icon
                      className={classNames(projectcss.all, sty.svg___5KvGq)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319333"}
                    data-plasmic-override={overrides.frame427319333}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319333)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Oh5U
                      )}
                    >
                      {"Collaboration Tools"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ofQMt
                      )}
                    >
                      {
                        "Enable peer-to-peer communication and teamwork through live chat, group projects, and discussion boards"
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts5"}
                  data-plasmic-override={overrides.qualityProducts5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts5)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319334"}
                    data-plasmic-override={overrides.frame427319334}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319334)}
                  >
                    <Frame34Icon
                      className={classNames(projectcss.all, sty.svg___1E8Bx)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319335"}
                    data-plasmic-override={overrides.frame427319335}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319335)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hXzRf
                      )}
                    >
                      {"Analytics and Reporting"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x544G
                      )}
                    >
                      {
                        "Track student performance with detailed reports, allowing teachers to identify learning gaps and offer timely interventions"
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts6"}
                  data-plasmic-override={overrides.qualityProducts6}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts6)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319336"}
                    data-plasmic-override={overrides.frame427319336}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319336)}
                  >
                    <Frame59Icon
                      className={classNames(projectcss.all, sty.svg__ylx8M)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319337"}
                    data-plasmic-override={overrides.frame427319337}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319337)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__b1QyC
                      )}
                    >
                      {"Remote and Hybrid Learning Support"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ddJw6
                      )}
                    >
                      {
                        "Cloud-based systems that support both in-person and remote learning for maximum flexibility."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"qualityProducts7"}
                  data-plasmic-override={overrides.qualityProducts7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.qualityProducts7)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319338"}
                    data-plasmic-override={overrides.frame427319338}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319338)}
                  >
                    <Frame51Icon
                      className={classNames(projectcss.all, sty.svg__zIjaE)}
                      role={"img"}
                    />
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame427319339"}
                    data-plasmic-override={overrides.frame427319339}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame427319339)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kDNq
                      )}
                    >
                      {"AI-Driven Insights"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g35Aw
                      )}
                    >
                      {
                        "Automate administrative tasks and predict student outcomes with AI-powered assessments and reporting."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"edtechSolutions"}
            data-plasmic-override={overrides.edtechSolutions}
            className={classNames(projectcss.all, sty.edtechSolutions)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__d3Fzs
              )}
            >
              {"Our EdTech Solutions"}
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__aKcHm)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iMg44
                )}
              >
                {"Custom EdTech for Modern Learning Environments"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ubbun
                )}
              >
                {
                  "We offer customized EdTech solutions designed for schools, universities, and vocational institutions, empowering educators to enhance learning experiences with technology that meets their specific needs and goals."
                }
              </div>
            </Stack__>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__t1JGa)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"1200px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/new_mv_technologies_website/images/image67.png",
                fullWidth: 10600,
                fullHeight: 4084,
                aspectRatio: undefined
              }}
            />

            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___0XNk2)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__py82H)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__px23H)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"q1"}
                    data-plasmic-override={overrides.q1}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.q1)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: (
                        <Frame59Icon
                          className={classNames(projectcss.all, sty.svg__zk3U4)}
                          role={"img"}
                        />
                      ),

                      value: args.q12
                    })}
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___2WGiV)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__i1229
                      )}
                    >
                      {"Learning Management Systems (LMS)"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gEgdM
                      )}
                    >
                      {
                        "Manage courses, assignments, and track student progress. Integrates easily with existing platforms."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__xHu7D)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"q14"}
                    data-plasmic-override={overrides.q14}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.q14)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: (
                        <Frame30Icon
                          className={classNames(projectcss.all, sty.svg__zsrYo)}
                          role={"img"}
                        />
                      ),

                      value: args.q13
                    })}
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fv6B6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__grYkv
                      )}
                    >
                      {"Student Information Systems (SIS)"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jvYt9
                      )}
                    >
                      {
                        "Handle enrollment, grading, attendance, and student record management efficiently."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__lhsqY)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"q16"}
                    data-plasmic-override={overrides.q16}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.q16)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: (
                        <Frame25Icon
                          className={classNames(projectcss.all, sty.svg__hHoeE)}
                          role={"img"}
                        />
                      ),

                      value: args.q15
                    })}
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wm5Df)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mLKru
                      )}
                    >
                      {"Classroom Management Software"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ak7W5
                      )}
                    >
                      {
                        "Support teachers with real-time classroom management tools to enhance digital learning experiences."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__u79Yf)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__zcsm6)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"q110"}
                    data-plasmic-override={overrides.q110}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.q110)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: (
                        <Frame16Icon
                          className={classNames(projectcss.all, sty.svg__zzUxh)}
                          role={"img"}
                        />
                      ),

                      value: args.q17
                    })}
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___37Jc)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eOpgj
                      )}
                    >
                      {"Collaboration & Communication Platforms"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h8H6
                      )}
                    >
                      {
                        "Seamlessly integrate with Microsoft Teams, Zoom, and other virtual collaboration tools"
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column___0UqOa)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"q111"}
                    data-plasmic-override={overrides.q111}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.q111)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: (
                        <Frame55Icon
                          className={classNames(projectcss.all, sty.svg__lUqe5)}
                          role={"img"}
                        />
                      ),

                      value: args.q18
                    })}
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vt9Ph)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__obQSp
                      )}
                    >
                      {"Assessment & Testing Tools"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ppe4W
                      )}
                    >
                      {
                        "Create interactive exams and quizzes to assess student knowledge accurately and efficiently"
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__cq2Zo)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"q112"}
                    data-plasmic-override={overrides.q112}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.q112)}
                  >
                    {renderPlasmicSlot({
                      defaultContents: (
                        <Frame50Icon
                          className={classNames(projectcss.all, sty.svg__wrb2)}
                          role={"img"}
                        />
                      ),

                      value: args.q19
                    })}
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__voR9Q)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ruznt
                      )}
                    >
                      {"Content Creation Platforms"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l6NBu
                      )}
                    >
                      {
                        "Empower teachers to build interactive lessons and presentations with tools like Nearpod and H5P."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"emergingTechnologies"}
            data-plasmic-override={overrides.emergingTechnologies}
            className={classNames(projectcss.all, sty.emergingTechnologies)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uEpit)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eXbPu
                )}
              >
                {"Emerging Technologies"}
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"ourServices"}
              data-plasmic-override={overrides.ourServices}
              hasGap={true}
              className={classNames(projectcss.all, sty.ourServices)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"outsourcingSoftware2"}
                data-plasmic-override={overrides.outsourcingSoftware2}
                hasGap={true}
                className={classNames(projectcss.all, sty.outsourcingSoftware2)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"text8"}
                  data-plasmic-override={overrides.text8}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.text8)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hXbGz)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/new_mv_technologies_website/images/image71.png",
                      fullWidth: 1000,
                      fullHeight: 470,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1VViH)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sPdcE
                      )}
                    >
                      {"Artificial Intelligence (AI)"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nKwYl
                      )}
                    >
                      {
                        "Leverage AI for personalized learning, grading automation, and predictive analysis."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"text10"}
                  data-plasmic-override={overrides.text10}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.text10)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__haCi3)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/new_mv_technologies_website/images/image74.png",
                      fullWidth: 1680,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__oTcVa)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__daXbm
                      )}
                    >
                      {"Virtual Reality (VR) & Augmented Reality (AR"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9QmPb
                      )}
                    >
                      {
                        "Offer immersive learning experiences through VR/AR for topics like science and history."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"text11"}
                  data-plasmic-override={overrides.text11}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.text11)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___67Fa4)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/new_mv_technologies_website/images/image73.png",
                      fullWidth: 1200,
                      fullHeight: 650,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1JdLg)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dlt7Y
                      )}
                    >
                      {"Block Chain"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pJm5Y
                      )}
                    >
                      {
                        "Ensure secure digital credentials and maintain academic records with blockchain technology."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"outsourcingSoftware4"}
                data-plasmic-override={overrides.outsourcingSoftware4}
                hasGap={true}
                className={classNames(projectcss.all, sty.outsourcingSoftware4)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"text12"}
                  data-plasmic-override={overrides.text12}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.text12)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kVQo)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/new_mv_technologies_website/images/image75.png",
                      fullWidth: 1920,
                      fullHeight: 768,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__hs5Er)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5ETEk
                      )}
                    >
                      {"Gamification"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dIZj
                      )}
                    >
                      {
                        "Increase student engagement by integrating game mechanics into learning modules."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"text13"}
                  data-plasmic-override={overrides.text13}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.text13)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mXtA)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/new_mv_technologies_website/images/image76.png",
                      fullWidth: 301,
                      fullHeight: 167,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qf8KW)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eeIdm
                      )}
                    >
                      {"Big Data & Analytics"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cBzk5
                      )}
                    >
                      {
                        "Utilize data to improve teaching strategies and optimize learning outcomes."
                      }
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"text14"}
                  data-plasmic-override={overrides.text14}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.text14)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hFUfn)}
                    displayHeight={"200px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/new_mv_technologies_website/images/image77.png",
                      fullWidth: 820,
                      fullHeight: 460,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__bnp8E)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__v0Ybu
                      )}
                    >
                      {"Internet of Things (IoT)"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__excge
                      )}
                    >
                      {
                        "Enable smart classrooms with IoT devices, from interactive whiteboards to smart projectors."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__sV80F)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8Rahb
                )}
              >
                {
                  "For more insights on the latest emerging technologies, don't hesitate to reach out to us\u2014we're here to help!"
                }
              </div>
              <Button2
                className={classNames("__wab_instance", sty.button2__ofprO)}
                endIcon={
                  <Frame18Icon
                    className={classNames(projectcss.all, sty.svg__ntaiu)}
                    role={"img"}
                  />
                }
                link={`/contact-page`}
                shape={"rounded"}
              >
                {"Contact Us"}
              </Button2>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"devOpsUseCases"}
            data-plasmic-override={overrides.devOpsUseCases}
            className={classNames(projectcss.all, sty.devOpsUseCases)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__abBbY)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hfwQ
                )}
              >
                {"ROI Metrics"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__veeYj)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lmPts)}
              >
                <div
                  data-plasmic-name={"line"}
                  data-plasmic-override={overrides.line}
                  className={classNames(projectcss.all, sty.line)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000975"}
                    data-plasmic-override={overrides.frame1000000975}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000975)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h6GgG
                      )}
                    >
                      {"1"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319348"}
                  data-plasmic-override={overrides.frame427319348}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319348)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i9Wsz
                    )}
                  >
                    {"Improved Learning Outcomes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aNJp
                    )}
                  >
                    {
                      "Better student outcomes lead to higher student retention rates, increased reputation, and potentially more enrollment, translating into direct financial gains for institutions."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___2B2Mg)}
              >
                <div
                  data-plasmic-name={"line2"}
                  data-plasmic-override={overrides.line2}
                  className={classNames(projectcss.all, sty.line2)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000977"}
                    data-plasmic-override={overrides.frame1000000977}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000977)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xWDeE
                      )}
                    >
                      {"2"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319349"}
                  data-plasmic-override={overrides.frame427319349}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319349)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fycjr
                    )}
                  >
                    {"Operational Efficiency and Cost Savings"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tyioa
                    )}
                  >
                    {
                      "Schools save on labor costs and time, while higher education institutions save on infrastructure costs, especially those implementing hybrid learning systems. Cost savings could range from 10% to 20% annually depending on the scale of adoption."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___0FEpC)}
              >
                <div
                  data-plasmic-name={"line3"}
                  data-plasmic-override={overrides.line3}
                  className={classNames(projectcss.all, sty.line3)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000979"}
                    data-plasmic-override={overrides.frame1000000979}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000979)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5DJnN
                      )}
                    >
                      {"3"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319340"}
                  data-plasmic-override={overrides.frame427319340}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319340)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vnP6S
                    )}
                  >
                    {"Increased Accessibility and Enrollment"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2Wwb2
                    )}
                  >
                    {
                      "Expanded student base due to increased accessibility and variety in program offerings leads to higher revenue for educational institutions. A 10% to 15% increase in enrollment can be expected."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__y6Oeb)}
              >
                <div
                  data-plasmic-name={"line4"}
                  data-plasmic-override={overrides.line4}
                  className={classNames(projectcss.all, sty.line4)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000984"}
                    data-plasmic-override={overrides.frame1000000984}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000984)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4H4Lg
                      )}
                    >
                      {"4"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319341"}
                  data-plasmic-override={overrides.frame427319341}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319341)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1QblZ
                    )}
                  >
                    {"Enhanced Teacher Efficiency and Retention"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kbQIl
                    )}
                  >
                    {
                      "Reduced teacher turnover and less reliance on external training programs save costs, while more efficient teachers can handle larger class sizes without compromising quality."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qqvL)}
              >
                <div
                  data-plasmic-name={"line5"}
                  data-plasmic-override={overrides.line5}
                  className={classNames(projectcss.all, sty.line5)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000987"}
                    data-plasmic-override={overrides.frame1000000987}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000987)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gYdg
                      )}
                    >
                      {"5"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319342"}
                  data-plasmic-override={overrides.frame427319342}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319342)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fugLh
                    )}
                  >
                    {"Scalability and Future-Proofing"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qsM3M
                    )}
                  >
                    {
                      "Long-term cost savings due to the scalable nature of the solution and reduced future upgrade costs by staying current with technological advancements."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rvPoM)}
              >
                <div
                  data-plasmic-name={"line6"}
                  data-plasmic-override={overrides.line6}
                  className={classNames(projectcss.all, sty.line6)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000988"}
                    data-plasmic-override={overrides.frame1000000988}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000988)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aQpLx
                      )}
                    >
                      {"6"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319343"}
                  data-plasmic-override={overrides.frame427319343}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319343)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f8AQ
                    )}
                  >
                    {"Competitive Differentiation and Brand Value"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pvK1Y
                    )}
                  >
                    {
                      "A stronger brand and higher perceived value can lead to premium pricing for programs, increased enrollment, and additional revenue through partnerships or sponsorships."
                    }
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__m2W0Y)}
              >
                <div
                  data-plasmic-name={"line7"}
                  data-plasmic-override={overrides.line7}
                  className={classNames(projectcss.all, sty.line7)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000000989"}
                    data-plasmic-override={overrides.frame1000000989}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000000989)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f22H3
                      )}
                    >
                      {"7"}
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame427319344"}
                  data-plasmic-override={overrides.frame427319344}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame427319344)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__im9W
                    )}
                  >
                    {"Long-Term Cost Efficiency"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bw9U5
                    )}
                  >
                    {
                      "Reductions in IT maintenance and content-related costs can lead to annual savings of 5%-10% for large institutions."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <ConnectWithUs
            data-plasmic-name={"connectWithUs"}
            data-plasmic-override={overrides.connectWithUs}
            className={classNames("__wab_instance", sty.connectWithUs)}
          />

          <NavFooter
            data-plasmic-name={"navFooter"}
            data-plasmic-override={overrides.navFooter}
            className={classNames("__wab_instance", sty.navFooter)}
          />

          <NavHeader
            data-plasmic-name={"navHeader"}
            data-plasmic-override={overrides.navHeader}
            className={classNames("__wab_instance", sty.navHeader)}
            scrolledVariant={(() => {
              try {
                return $ctx.isScrolled;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection",
    "whyChooseVidyayatan",
    "qualityProducts",
    "frame427319326",
    "frame427319327",
    "qualityProducts2",
    "frame427319328",
    "frame427319329",
    "qualityProducts3",
    "frame427319330",
    "frame427319331",
    "convertSection",
    "whyChooseVidyayatan2",
    "qualityProducts4",
    "frame427319332",
    "frame427319333",
    "qualityProducts5",
    "frame427319334",
    "frame427319335",
    "qualityProducts6",
    "frame427319336",
    "frame427319337",
    "qualityProducts7",
    "frame427319338",
    "frame427319339",
    "edtechSolutions",
    "q1",
    "q14",
    "q16",
    "q110",
    "q111",
    "q112",
    "emergingTechnologies",
    "ourServices",
    "outsourcingSoftware2",
    "text8",
    "text10",
    "text11",
    "outsourcingSoftware4",
    "text12",
    "text13",
    "text14",
    "devOpsUseCases",
    "line",
    "frame1000000975",
    "frame427319348",
    "line2",
    "frame1000000977",
    "frame427319349",
    "line3",
    "frame1000000979",
    "frame427319340",
    "line4",
    "frame1000000984",
    "frame427319341",
    "line5",
    "frame1000000987",
    "frame427319342",
    "line6",
    "frame1000000988",
    "frame427319343",
    "line7",
    "frame1000000989",
    "frame427319344",
    "connectWithUs",
    "navFooter",
    "navHeader"
  ],
  heroSection: ["heroSection"],
  whyChooseVidyayatan: [
    "whyChooseVidyayatan",
    "qualityProducts",
    "frame427319326",
    "frame427319327",
    "qualityProducts2",
    "frame427319328",
    "frame427319329",
    "qualityProducts3",
    "frame427319330",
    "frame427319331"
  ],
  qualityProducts: ["qualityProducts", "frame427319326", "frame427319327"],
  frame427319326: ["frame427319326"],
  frame427319327: ["frame427319327"],
  qualityProducts2: ["qualityProducts2", "frame427319328", "frame427319329"],
  frame427319328: ["frame427319328"],
  frame427319329: ["frame427319329"],
  qualityProducts3: ["qualityProducts3", "frame427319330", "frame427319331"],
  frame427319330: ["frame427319330"],
  frame427319331: ["frame427319331"],
  convertSection: ["convertSection"],
  whyChooseVidyayatan2: [
    "whyChooseVidyayatan2",
    "qualityProducts4",
    "frame427319332",
    "frame427319333",
    "qualityProducts5",
    "frame427319334",
    "frame427319335",
    "qualityProducts6",
    "frame427319336",
    "frame427319337",
    "qualityProducts7",
    "frame427319338",
    "frame427319339"
  ],
  qualityProducts4: ["qualityProducts4", "frame427319332", "frame427319333"],
  frame427319332: ["frame427319332"],
  frame427319333: ["frame427319333"],
  qualityProducts5: ["qualityProducts5", "frame427319334", "frame427319335"],
  frame427319334: ["frame427319334"],
  frame427319335: ["frame427319335"],
  qualityProducts6: ["qualityProducts6", "frame427319336", "frame427319337"],
  frame427319336: ["frame427319336"],
  frame427319337: ["frame427319337"],
  qualityProducts7: ["qualityProducts7", "frame427319338", "frame427319339"],
  frame427319338: ["frame427319338"],
  frame427319339: ["frame427319339"],
  edtechSolutions: [
    "edtechSolutions",
    "q1",
    "q14",
    "q16",
    "q110",
    "q111",
    "q112"
  ],
  q1: ["q1"],
  q14: ["q14"],
  q16: ["q16"],
  q110: ["q110"],
  q111: ["q111"],
  q112: ["q112"],
  emergingTechnologies: [
    "emergingTechnologies",
    "ourServices",
    "outsourcingSoftware2",
    "text8",
    "text10",
    "text11",
    "outsourcingSoftware4",
    "text12",
    "text13",
    "text14"
  ],
  ourServices: [
    "ourServices",
    "outsourcingSoftware2",
    "text8",
    "text10",
    "text11",
    "outsourcingSoftware4",
    "text12",
    "text13",
    "text14"
  ],
  outsourcingSoftware2: ["outsourcingSoftware2", "text8", "text10", "text11"],
  text8: ["text8"],
  text10: ["text10"],
  text11: ["text11"],
  outsourcingSoftware4: ["outsourcingSoftware4", "text12", "text13", "text14"],
  text12: ["text12"],
  text13: ["text13"],
  text14: ["text14"],
  devOpsUseCases: [
    "devOpsUseCases",
    "line",
    "frame1000000975",
    "frame427319348",
    "line2",
    "frame1000000977",
    "frame427319349",
    "line3",
    "frame1000000979",
    "frame427319340",
    "line4",
    "frame1000000984",
    "frame427319341",
    "line5",
    "frame1000000987",
    "frame427319342",
    "line6",
    "frame1000000988",
    "frame427319343",
    "line7",
    "frame1000000989",
    "frame427319344"
  ],
  line: ["line", "frame1000000975"],
  frame1000000975: ["frame1000000975"],
  frame427319348: ["frame427319348"],
  line2: ["line2", "frame1000000977"],
  frame1000000977: ["frame1000000977"],
  frame427319349: ["frame427319349"],
  line3: ["line3", "frame1000000979"],
  frame1000000979: ["frame1000000979"],
  frame427319340: ["frame427319340"],
  line4: ["line4", "frame1000000984"],
  frame1000000984: ["frame1000000984"],
  frame427319341: ["frame427319341"],
  line5: ["line5", "frame1000000987"],
  frame1000000987: ["frame1000000987"],
  frame427319342: ["frame427319342"],
  line6: ["line6", "frame1000000988"],
  frame1000000988: ["frame1000000988"],
  frame427319343: ["frame427319343"],
  line7: ["line7", "frame1000000989"],
  frame1000000989: ["frame1000000989"],
  frame427319344: ["frame427319344"],
  connectWithUs: ["connectWithUs"],
  navFooter: ["navFooter"],
  navHeader: ["navHeader"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroSection: "section";
  whyChooseVidyayatan: "section";
  qualityProducts: "div";
  frame427319326: "div";
  frame427319327: "div";
  qualityProducts2: "div";
  frame427319328: "div";
  frame427319329: "div";
  qualityProducts3: "div";
  frame427319330: "div";
  frame427319331: "div";
  convertSection: "section";
  whyChooseVidyayatan2: "section";
  qualityProducts4: "div";
  frame427319332: "div";
  frame427319333: "div";
  qualityProducts5: "div";
  frame427319334: "div";
  frame427319335: "div";
  qualityProducts6: "div";
  frame427319336: "div";
  frame427319337: "div";
  qualityProducts7: "div";
  frame427319338: "div";
  frame427319339: "div";
  edtechSolutions: "section";
  q1: "div";
  q14: "div";
  q16: "div";
  q110: "div";
  q111: "div";
  q112: "div";
  emergingTechnologies: "section";
  ourServices: "div";
  outsourcingSoftware2: "div";
  text8: "div";
  text10: "div";
  text11: "div";
  outsourcingSoftware4: "div";
  text12: "div";
  text13: "div";
  text14: "div";
  devOpsUseCases: "section";
  line: "div";
  frame1000000975: "div";
  frame427319348: "div";
  line2: "div";
  frame1000000977: "div";
  frame427319349: "div";
  line3: "div";
  frame1000000979: "div";
  frame427319340: "div";
  line4: "div";
  frame1000000984: "div";
  frame427319341: "div";
  line5: "div";
  frame1000000987: "div";
  frame427319342: "div";
  line6: "div";
  frame1000000988: "div";
  frame427319343: "div";
  line7: "div";
  frame1000000989: "div";
  frame427319344: "div";
  connectWithUs: typeof ConnectWithUs;
  navFooter: typeof NavFooter;
  navHeader: typeof NavHeader;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEdtechPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEdtechPage__VariantsArgs;
    args?: PlasmicEdtechPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicEdtechPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicEdtechPage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEdtechPage__ArgProps,
          internalVariantPropNames: PlasmicEdtechPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEdtechPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEdtechPage";
  } else {
    func.displayName = `PlasmicEdtechPage.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "qg9BUJrNtisePZMs8FM4BQ"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicEdtechPage = Object.assign(
  // Top-level PlasmicEdtechPage renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    heroSection: makeNodeComponent("heroSection"),
    whyChooseVidyayatan: makeNodeComponent("whyChooseVidyayatan"),
    qualityProducts: makeNodeComponent("qualityProducts"),
    frame427319326: makeNodeComponent("frame427319326"),
    frame427319327: makeNodeComponent("frame427319327"),
    qualityProducts2: makeNodeComponent("qualityProducts2"),
    frame427319328: makeNodeComponent("frame427319328"),
    frame427319329: makeNodeComponent("frame427319329"),
    qualityProducts3: makeNodeComponent("qualityProducts3"),
    frame427319330: makeNodeComponent("frame427319330"),
    frame427319331: makeNodeComponent("frame427319331"),
    convertSection: makeNodeComponent("convertSection"),
    whyChooseVidyayatan2: makeNodeComponent("whyChooseVidyayatan2"),
    qualityProducts4: makeNodeComponent("qualityProducts4"),
    frame427319332: makeNodeComponent("frame427319332"),
    frame427319333: makeNodeComponent("frame427319333"),
    qualityProducts5: makeNodeComponent("qualityProducts5"),
    frame427319334: makeNodeComponent("frame427319334"),
    frame427319335: makeNodeComponent("frame427319335"),
    qualityProducts6: makeNodeComponent("qualityProducts6"),
    frame427319336: makeNodeComponent("frame427319336"),
    frame427319337: makeNodeComponent("frame427319337"),
    qualityProducts7: makeNodeComponent("qualityProducts7"),
    frame427319338: makeNodeComponent("frame427319338"),
    frame427319339: makeNodeComponent("frame427319339"),
    edtechSolutions: makeNodeComponent("edtechSolutions"),
    q1: makeNodeComponent("q1"),
    q14: makeNodeComponent("q14"),
    q16: makeNodeComponent("q16"),
    q110: makeNodeComponent("q110"),
    q111: makeNodeComponent("q111"),
    q112: makeNodeComponent("q112"),
    emergingTechnologies: makeNodeComponent("emergingTechnologies"),
    ourServices: makeNodeComponent("ourServices"),
    outsourcingSoftware2: makeNodeComponent("outsourcingSoftware2"),
    text8: makeNodeComponent("text8"),
    text10: makeNodeComponent("text10"),
    text11: makeNodeComponent("text11"),
    outsourcingSoftware4: makeNodeComponent("outsourcingSoftware4"),
    text12: makeNodeComponent("text12"),
    text13: makeNodeComponent("text13"),
    text14: makeNodeComponent("text14"),
    devOpsUseCases: makeNodeComponent("devOpsUseCases"),
    line: makeNodeComponent("line"),
    frame1000000975: makeNodeComponent("frame1000000975"),
    frame427319348: makeNodeComponent("frame427319348"),
    line2: makeNodeComponent("line2"),
    frame1000000977: makeNodeComponent("frame1000000977"),
    frame427319349: makeNodeComponent("frame427319349"),
    line3: makeNodeComponent("line3"),
    frame1000000979: makeNodeComponent("frame1000000979"),
    frame427319340: makeNodeComponent("frame427319340"),
    line4: makeNodeComponent("line4"),
    frame1000000984: makeNodeComponent("frame1000000984"),
    frame427319341: makeNodeComponent("frame427319341"),
    line5: makeNodeComponent("line5"),
    frame1000000987: makeNodeComponent("frame1000000987"),
    frame427319342: makeNodeComponent("frame427319342"),
    line6: makeNodeComponent("line6"),
    frame1000000988: makeNodeComponent("frame1000000988"),
    frame427319343: makeNodeComponent("frame427319343"),
    line7: makeNodeComponent("line7"),
    frame1000000989: makeNodeComponent("frame1000000989"),
    frame427319344: makeNodeComponent("frame427319344"),
    connectWithUs: makeNodeComponent("connectWithUs"),
    navFooter: makeNodeComponent("navFooter"),
    navHeader: makeNodeComponent("navHeader"),

    // Metadata about props expected for PlasmicEdtechPage
    internalVariantProps: PlasmicEdtechPage__VariantProps,
    internalArgProps: PlasmicEdtechPage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicEdtechPage;
/* prettier-ignore-end */
